# ================================================================
#  CREA 20072 — Configurazione PagesCMS
#  Percorso: pages.yml  (nella cartella principale del sito)
#  NON modificare questo file.
# ================================================================

media:
  input: ""
  output: ""

content:
  - name: site_data
    label: "Contenuti Sito"
    type: file
    path: data/content.json
    fields:

      - name: settings
        label: "Impostazioni"
        type: object
        fields:
          - name: logo
            label: Logo del sito
            type: image
          - name: formspreeUrl
            label: "Link Formspree (opzionale - per ricevere email dal form contatti)"
            type: string

      - name: hero
        label: "Copertina"
        type: object
        fields:
          - name: title
            label: Titolo principale
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: cta
            label: Testo del bottone
            type: string
          - name: bg
            label: Immagine di sfondo
            type: image

      - name: about
        label: "Chi Siamo"
        type: object
        fields:
          - name: title
            label: Titolo sezione
            type: string
          - name: text
            label: Testo descrittivo
            type: text
          - name: tagline
            label: Frase finale (piccola, in basso)
            type: string
          - name: pillars
            label: I tre valori
            type: list
            fields:
              - name: icon
                label: "Icona (nome Lucide, es: users, heart, sparkles)"
                type: string
              - name: t
                label: Titolo
                type: string
              - name: d
                label: Descrizione
                type: string

      - name: featuredEvent
        label: "Prossimo Evento"
        type: object
        fields:
          - name: title
            label: Nome evento
            type: string
          - name: sub
            label: Sottotitolo o Artista
            type: string
          - name: day
            label: "Giorno (2 cifre: 01, 15, 28...)"
            type: string
          - name: month
            label: "Mese abbreviato maiuscolo (GEN, FEB, MAR, APR, MAG, GIU, LUG, AGO, SET, OTT, NOV, DIC)"
            type: string
          - name: fullDate
            label: "Data completa (es: Domenica 1 Marzo 2026 - Ore 16:00)"
            type: string
          - name: place
            label: Luogo
            type: string
          - name: prices
            label: Prezzi
            type: string
          - name: desc
            label: Descrizione
            type: text
          - name: wa
            label: "Link WhatsApp prenotazioni (es: https://wa.me/393402231735)"
            type: string
          - name: img
            label: "Locandina - consigliato 600x900px (verticale). I flyer Instagram vanno benissimo."
            type: image

      - name: archive
        label: "Archivio Eventi Passati"
        type: list
        fields:
          - name: id
            label: "ID univoco (numero progressivo: 1, 2, 3...)"
            type: number
          - name: date
            label: "Data per ordinamento automatico (formato: AAAA-MM-GG, es: 2026-03-01)"
            type: string
          - name: t
            label: Nome evento
            type: string
          - name: d
            label: "Data leggibile (es: Marzo 2026) - mostrata nel sito"
            type: string
          - name: tag
            label: Categoria
            type: select
            options:
              - value: famiglie
                label: Famiglie
              - value: tradizioni
                label: Tradizioni
              - value: spettacoli
                label: Spettacoli
          - name: n
            label: "Info breve (es: Sold Out, 150+ persone, 100 bambini...)"
            type: string
          - name: desc
            label: "Descrizione breve - mostrata nella card della griglia"
            type: string
          - name: fullDesc
            label: "Descrizione completa - mostrata aprendo la scheda evento"
            type: text
          - name: img
            label: "Immagine card - consigliato 800x600px (orizzontale) o 800x800px (quadrata)"
            type: image
          - name: gallery
            label: "Foto galleria (opzionale) - cliccabili a schermo intero"
            type: list
            fields:
              - name: url
                label: Foto
                type: image

      - name: decalogo
        label: "Decalogo"
        type: object
        fields:
          - name: title
            label: Titolo sezione
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: items
            label: Le 10 regole
            type: list
            fields:
              - name: n
                label: "Numero (01, 02, 03...)"
                type: string
              - name: t
                label: Titolo regola
                type: string
              - name: d
                label: Descrizione
                type: string
              - name: i
                label: "Icona Lucide (es: home, smile, clock, users, award...)"
                type: string

      - name: footer
        label: "Footer e Contatti"
        type: object
        fields:
          - name: email
            label: Email di contatto
            type: string
          - name: quote
            label: Frase ispirazionale
            type: string
          - name: socials
            label: Link Social
            type: list
            fields:
              - name: icon
                label: Piattaforma
                type: select
                options:
                  - value: facebook
                    label: Facebook
                  - value: instagram
                    label: Instagram
                  - value: whatsapp
                    label: WhatsApp
              - name: url
                label: Link profilo completo
                type: string
