# Configurazione per Pages CMS aggiornata e corretta

media:
  input: "."
  output: "."

content:
  - name: site_data
    label: "Gestione Contenuti Sito"
    type: file
    path: data/content.json
    fields:
      - name: settings
        label: "⚙️ Impostazioni Generali"
        type: object
        fields:
          - { name: logo, label: "Logo del Sito", type: image }
          - { name: brandColor, label: "Colore Principale (Hex)", type: string }
          - { name: honeyLight, label: "Sfondo Chiaro (Hex)", type: string }
          - { name: formspreeUrl, label: "Link Formspree", type: string }

      - name: footer
        label: "👇 Piè di Pagina"
        type: object
        fields:
          - { name: email, label: "Email Contatti", type: string }
          - { name: quote, label: "Frase Ispirazionale", type: string }
          - name: socials
            label: "Link Social"
            type: object
            list: true
            fields:
              - { name: icon, label: "Icona (facebook/instagram)", type: string }
              - { name: url, label: "Link Completo", type: string }

      - name: hero
        label: "🏠 Home Page (Copertina)"
        type: object
        fields:
          - { name: title, label: "Titolo Grande", type: string }
          - { name: subtitle, label: "Sottotitolo", type: string }
          - { name: cta, label: "Testo Bottone", type: string }
          - { name: bg, label: "Immagine di Sfondo", type: image }

      - name: about
        label: "ℹ️ Chi Siamo"
        type: object
        fields:
          - { name: title, label: "Titolo Sezione", type: string }
          - { name: text, label: "Testo Descrittivo", type: text }
          - { name: tagline, label: "Frase Finale", type: string }
          - name: pillars
            label: "I 3 Pilastri"
            type: object
            list: true
            fields:
              - { name: icon, label: "Icona Lucide", type: string }
              - { name: t, label: "Titolo", type: string }
              - { name: d, label: "Descrizione", type: string }

      - name: decalogo
        label: "📜 Il Decalogo"
        type: object
        fields:
          - { name: title, label: "Titolo", type: string }
          - { name: subtitle, label: "Sottotitolo", type: string }
          - name: items
            label: "I 10 Punti"
            type: object
            list: true
            fields:
              - { name: n, label: "Numero", type: string }
              - { name: t, label: "Titolo", type: string }
              - { name: d, label: "Spiegazione", type: string }
              - { name: i, label: "Icona", type: string }

      - name: featuredEvent
        label: "⭐️ PROSSIMO EVENTO"
        type: object
        fields:
          - { name: title, label: "Titolo Evento", type: string }
          - { name: sub, label: "Sottotitolo", type: string }
          - { name: day, label: "Giorno (es: 01)", type: string }
          - { name: month, label: "Mese (es: MAR)", type: string }
          - { name: fullDate, label: "Data Completa", type: string }
          - { name: place, label: "Luogo", type: string }
          - { name: prices, label: "Prezzi", type: string }
          - { name: desc, label: "Descrizione", type: text }
          - { name: wa, label: "Link WhatsApp", type: string }
          - { name: img, label: "Locandina Verticale", type: image }

      - name: archive
        label: "📚 ARCHIVIO STORICO"
        type: object
        list: true
        fields:
          - { name: id, label: "ID Univoco (es: 1, 2, 3)", type: number }
          - { name: t, label: "Titolo Evento", type: string }
          - { name: d, label: "Data (es: Gennaio 2026)", type: string }
          - { name: tag, label: "Categoria", type: select, options: ["tradizioni", "famiglie", "spettacoli"] }
          - { name: n, label: "Dettaglio (es: Sold Out)", type: string }
          - { name: desc, label: "Descrizione Breve", type: string }
          - { name: fullDesc, label: "Descrizione Completa (per popup)", type: text }
          - { name: img, label: "Foto Copertina", type: image }
          - name: gallery
            label: "Galleria Foto Extra"
            type: image
            list: true