# ================================================================
#  CREA 20072 — Configurazione PagesCMS
#  Percorso: pages.yml  (nella cartella principale del sito)
# ================================================================
#
#  Questo file dice a PagesCMS quali campi mostrare nell'editor.
#  NON modificarlo: è già configurato per funzionare con il sito.
#
# ================================================================

media:
  input: ""       # Le immagini vanno caricate nella cartella principale
  output: ""

content:
  - name: site_data
    label: "✏️ Contenuti Sito"
    type: file
    path: data/content.js        # ← punta al file JS corretto
    format: javascript-export    # formato window.DATA_STORE = { ... }
    fields:

      # -------------------------------------------------------
      - name: settings
        label: "⚙️ Impostazioni"
        type: object
        fields:
          - name: logo
            label: Logo del sito
            type: image
          - name: formspreeUrl
            label: "Link Formspree (opzionale — per ricevere email dal form)"
            type: string

      # -------------------------------------------------------
      - name: hero
        label: "🖼️ Copertina"
        type: object
        fields:
          - name: title
            label: Titolo principale
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: cta
            label: Testo del bottone
            type: string
          - name: bg
            label: Immagine di sfondo
            type: image

      # -------------------------------------------------------
      - name: about
        label: "👋 Chi Siamo"
        type: object
        fields:
          - name: title
            label: Titolo sezione
            type: string
          - name: text
            label: Testo descrittivo
            type: text
          - name: tagline
            label: Frase finale (piccola, in basso)
            type: string
          - name: pillars
            label: I tre valori
            type: list
            fields:
              - name: icon
                label: "Icona (nome Lucide, es: users, heart, sparkles)"
                type: string
              - name: t
                label: Titolo
                type: string
              - name: d
                label: Descrizione
                type: string

      # -------------------------------------------------------
      - name: featuredEvent
        label: "🌟 Prossimo Evento"
        type: object
        fields:
          - name: title
            label: Nome evento
            type: string
          - name: sub
            label: Sottotitolo / Artista
            type: string
          - name: day
            label: "Giorno (2 cifre: 01, 15, 28...)"
            type: string
          - name: month
            label: "Mese abbreviato (GEN, FEB, MAR...)"
            type: string
          - name: fullDate
            label: "Data completa (es: Domenica 1 Marzo 2026 – Ore 16:00)"
            type: string
          - name: place
            label: Luogo
            type: string
          - name: prices
            label: Prezzi
            type: string
          - name: desc
            label: Descrizione
            type: text
          - name: wa
            label: "Link WhatsApp prenotazioni (es: https://wa.me/393402231735)"
            type: string
          - name: img
            label: Locandina
            type: image

      # -------------------------------------------------------
      - name: archive
        label: "📁 Archivio Eventi Passati"
        type: list
        fields:
          - name: id
            label: "ID (numero progressivo: 1, 2, 3...)"
            type: number
          - name: t
            label: Nome evento
            type: string
          - name: d
            label: "Data (es: Ottobre 2025)"
            type: string
          - name: tag
            label: Categoria
            type: select
            options:
              - value: famiglie
                label: Famiglie
              - value: tradizioni
                label: Tradizioni
              - value: spettacoli
                label: Spettacoli
          - name: n
            label: "Info extra (es: Sold Out, 150+ persone...)"
            type: string
          - name: desc
            label: Descrizione breve (visibile nella card)
            type: string
          - name: fullDesc
            label: Descrizione completa (visibile aprendo la scheda)
            type: text
          - name: img
            label: Immagine di copertina
            type: image
          - name: gallery
            label: Galleria foto (opzionale)
            type: list
            fields:
              - name: url
                label: Foto
                type: image

      # -------------------------------------------------------
      - name: decalogo
        label: "📜 Decalogo"
        type: object
        fields:
          - name: title
            label: Titolo sezione
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: items
            label: Le 10 regole
            type: list
            fields:
              - name: n
                label: "Numero (01, 02...)"
                type: string
              - name: t
                label: Titolo regola
                type: string
              - name: d
                label: Descrizione
                type: string
              - name: i
                label: "Icona (nome Lucide, es: home, smile, clock...)"
                type: string

      # -------------------------------------------------------
      - name: footer
        label: "📬 Footer e Contatti"
        type: object
        fields:
          - name: email
            label: Email di contatto
            type: string
          - name: quote
            label: Frase ispirazionale
            type: string
          - name: socials
            label: Link Social
            type: list
            fields:
              - name: icon
                label: "Piattaforma (facebook, instagram, whatsapp)"
                type: select
                options:
                  - value: facebook
                    label: Facebook
                  - value: instagram
                    label: Instagram
                  - value: whatsapp
                    label: WhatsApp
              - name: url
                label: Link profilo
                type: string
