# ================================================================
#  CREA 20072 — Configurazione PagesCMS
#  Percorso: pages.yml  (nella cartella principale del sito)
#  NON modificare questo file.
#
#  NOTA: Alcune sezioni (Chi Siamo - tre valori, Decalogo, Social)
#  non appaiono qui perché PagesCMS non supporta liste annidate
#  dentro oggetti. Modificale direttamente in data/content.json
#  su GitHub — cambiano raramente.
# ================================================================

media:
  input: ""
  output: ""

content:
  - name: site_data
    label: "Contenuti Sito"
    type: file
    path: data/content.json
    fields:

      # ── Impostazioni ──────────────────────────────────────────
      - name: settings
        label: "Impostazioni"
        type: object
        fields:
          - name: logo
            label: Logo del sito
            type: image
          - name: formspreeUrl
            label: "Link Formspree (opzionale - per ricevere email dal form)"
            type: string

      # ── Copertina ─────────────────────────────────────────────
      - name: hero
        label: "Copertina"
        type: object
        fields:
          - name: title
            label: Titolo principale
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: cta
            label: Testo del bottone
            type: string
          - name: bg
            label: Immagine di sfondo
            type: image

      # ── Chi Siamo (solo testi, non i tre valori) ──────────────
      - name: about
        label: "Chi Siamo"
        type: object
        fields:
          - name: title
            label: Titolo sezione
            type: string
          - name: text
            label: Testo descrittivo
            type: text
          - name: tagline
            label: Frase finale (piccola, in basso)
            type: string

      # ── Prossimo Evento ───────────────────────────────────────
      - name: featuredEvent
        label: "Prossimo Evento"
        type: object
        fields:
          - name: title
            label: Nome evento
            type: string
          - name: sub
            label: Sottotitolo o Artista
            type: string
          - name: day
            label: "Giorno (2 cifre: 01, 15, 28...)"
            type: string
          - name: month
            label: "Mese (GEN, FEB, MAR, APR, MAG, GIU, LUG, AGO, SET, OTT, NOV, DIC)"
            type: string
          - name: fullDate
            label: "Data completa (es: Domenica 1 Marzo 2026 - Ore 16:00)"
            type: string
          - name: place
            label: Luogo
            type: string
          - name: prices
            label: Prezzi
            type: string
          - name: desc
            label: Descrizione
            type: text
          - name: wa
            label: "Link WhatsApp prenotazioni (es: https://wa.me/393402231735)"
            type: string
          - name: img
            label: "Locandina (600x900px consigliato - i flyer Instagram vanno benissimo)"
            type: image

      # ── Archivio Eventi ───────────────────────────────────────
      - name: archive
        label: "Archivio Eventi Passati"
        type: list
        fields:
          - name: id
            label: "ID univoco (numero progressivo: 1, 2, 3...)"
            type: number
          - name: date
            label: "Data ordinamento automatico (AAAA-MM-GG, es: 2026-03-01)"
            type: string
          - name: t
            label: Nome evento
            type: string
          - name: d
            label: "Data leggibile (es: Marzo 2026)"
            type: string
          - name: tag
            label: Categoria
            type: select
            options:
              - value: famiglie
                label: Famiglie
              - value: tradizioni
                label: Tradizioni
              - value: spettacoli
                label: Spettacoli
          - name: n
            label: "Info breve (es: Sold Out, 150+ persone...)"
            type: string
          - name: desc
            label: Descrizione breve (nella card)
            type: string
          - name: fullDesc
            label: Descrizione completa (nella scheda)
            type: text
          - name: img
            label: "Immagine card (800x600px o 800x800px consigliato)"
            type: image

      # ── Footer ────────────────────────────────────────────────
      - name: footer
        label: "Footer e Contatti"
        type: object
        fields:
          - name: email
            label: Email di contatto
            type: string
          - name: quote
            label: Frase ispirazionale
            type: string
