media:
  input: "."
  output: "."

content:
  - name: site_data
    label: Contenuti Sito
    type: file
    path: data/content.json
    fields:
      - name: settings
        label: Impostazioni Generali
        type: object
        fields:
          - name: logo
            label: Logo del Sito
            type: image
          - name: brandColor
            label: Colore Principale
            type: string
          - name: honeyLight
            label: Sfondo Chiaro
            type: string
          - name: formspreeUrl
            label: Link Formspree
            type: string

      - name: footer
        label: Pie di Pagina
        type: object
        fields:
          - name: email
            label: Email Contatti
            type: string
          - name: quote
            label: Frase Ispirazionale
            type: string
          - name: socials
            label: Link Social
            type: object
            list: true
            fields:
              - name: icon
                label: Icona (es. facebook)
                type: string
              - name: url
                label: Link
                type: string

      - name: hero
        label: Copertina
        type: object
        fields:
          - name: title
            label: Titolo
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: cta
            label: Testo Bottone
            type: string
          - name: bg
            label: Sfondo
            type: image

      - name: about
        label: Chi Siamo
        type: object
        fields:
          - name: title
            label: Titolo
            type: string
          - name: text
            label: Testo
            type: string
          - name: tagline
            label: Sottotitolo
            type: string
          - name: pillars
            label: Pilastri
            type: object
            list: true
            fields:
              - name: icon
                label: Icona
                type: string
              - name: t
                label: Titolo
                type: string
              - name: d
                label: Descrizione
                type: string

      - name: decalogo
        label: Decalogo
        type: object
        fields:
          - name: title
            label: Titolo
            type: string
          - name: subtitle
            label: Sottotitolo
            type: string
          - name: items
            label: Regole
            type: object
            list: true
            fields:
              - name: n
                label: Numero
                type: string
              - name: t
                label: Titolo
                type: string
              - name: d
                label: Descrizione
                type: string
              - name: i
                label: Icona
                type: string

      - name: featuredEvent
        label: Prossimo Evento
        type: object
        fields:
          - name: title
            label: Titolo
            type: string
          - name: sub
            label: Sottotitolo
            type: string
          - name: day
            label: Giorno
            type: string
          - name: month
            label: Mese
            type: string
          - name: fullDate
            label: Data Completa
            type: string
          - name: place
            label: Luogo
            type: string
          - name: prices
            label: Prezzi
            type: string
          - name: desc
            label: Descrizione
            type: string
          - name: wa
            label: Link WhatsApp
            type: string
          - name: img
            label: Locandina
            type: image

      - name: archive
        label: Archivio Eventi
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: number
          - name: t
            label: Titolo
            type: string
          - name: d
            label: Data
            type: string
          - name: tag
            label: Categoria (scrivi tradizioni, famiglie o spettacoli)
            type: string
          - name: n
            label: Dettaglio Extra
            type: string
          - name: desc
            label: Descrizione Breve
            type: string
          - name: fullDesc
            label: Descrizione Completa
            type: string
          - name: img
            label: Foto Copertina
            type: image
          - name: gallery
            label: Galleria Extra
            type: image
            list: true
